#!/bin/sh

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZSHZ_DATA="$XDG_STATE_HOME/z"

export ANDROID_HOME="$HOME/Library/Android/sdk"
export JAVA_HOME="$(/usr/libexec/java_home -v 17)"

export MISE_DIR="$XDG_CONFIG_HOME/mise"
export MISE_NODE_DEFAULT_PACKAGES_FILE="$MISE_DIR/.default-npm-packages"
export MISE_PYTHON_DEFAULT_PACKAGES_FILE="$MISE_DIR/.default-python-packages"
export MISE_RUBY_DEFAULT_PACKAGES_FILE="$MISE_DIR/.default-gems"

export EDITOR="code --wait"
export VISUAL="code"
export LANG="en_US.UTF-8"
export LANGUAGE="en"
export LC_ALL="en_US.UTF-8"

export PATH="$ANDROID_HOME/tools/bin:$PATH"
export PATH="$ANDROID_HOME/tools:$PATH"
export PATH="$ANDROID_HOME/platform-tools:$PATH"
export PATH="$ANDROID_HOME/emulator:$PATH"
export PATH="$HOME/.local/share/mise/shims:$PATH" # Activate Mise shims

eval "$(/opt/homebrew/bin/brew shellenv)"
