#!/bin/sh

export XDG_BIN_HOME="$HOME/.local/bin"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export FZF_DEFAULT_COMMAND="fd --strip-cwd-prefix --follow --hidden --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND --type directory"

export ANDROID_HOME="$HOME/Library/Android/sdk"
export JAVA_HOME="$(/usr/libexec/java_home -v 17)"

export MISE_CONFIG_DIR="$XDG_CONFIG_HOME/mise"
export MISE_DATA_DIR="$XDG_DATA_HOME/mise"
export MISE_NODE_DEFAULT_PACKAGES_FILE="$MISE_CONFIG_DIR/.default-npm-packages"

export BAT_THEME_LIGHT="OneHalfLight"
export BAT_THEME_DARK="OneHalfDark"

export EDITOR="code --wait"
export VISUAL="code"
export LANG="en_US.UTF-8"
export LANGUAGE="en"
export LC_ALL="en_US.UTF-8"

export PATH="$ANDROID_HOME/tools/bin:$PATH"
export PATH="$ANDROID_HOME/tools:$PATH"
export PATH="$ANDROID_HOME/platform-tools:$PATH"
export PATH="$ANDROID_HOME/emulator:$PATH"
export PATH="$XDG_BIN_HOME:$PATH" # Add local binaries like Mise and Chezmoi to the PATH

eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(mise activate zsh --shims)" # Ensure Mise's binaries take precedence over Homebrew's
