[tools]
node = "lts"
"npm:@antfu/ni" = "latest"
"npm:npm-check-updates" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
minimum_release_age = "7d" # Only install versions released more than 7 days ago
