# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json

gui:
  nerdFontsVersion: "3"
  expandFocusedSidePanel: true
  shrinkSidePanelsToContent: true

git:
  pagers:
    - pager: ~/.config/lazygit/theme-aware-delta.sh --paging=never
