#!/bin/sh

typeset -U path # Prevents duplicate entries on the PATH

# Plugins
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
    source "$XDG_CACHE_HOME/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source "$XDG_DATA_HOME/zap/zap.zsh"
eval "$(rbenv init - zsh)"

plug "zap-zsh/supercharge"
plug "agkozak/zsh-z"
plug "$ZDOTDIR/aliases.zsh"
plug "$ZDOTDIR/git.zsh"

if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
    plug "zsh-users/zsh-syntax-highlighting"
    plug "zsh-users/zsh-autosuggestions"
    plug "zsh-users/zsh-history-substring-search"
    plug "romkatv/powerlevel10k"
    plug "$ZDOTDIR/.p10k.zsh"
fi

# Path
path+=$N_PREFIX/bin
path+=$ANDROID_HOME/tools/bin
path+=$ANDROID_HOME/tools
path+=$ANDROID_HOME/platform-tools
path+=$ANDROID_HOME/emulator
path=('/opt/homebrew/bin' '/opt/homebrew/sbin' $path) # Ensure Homebrew installed binaries take precedence
export PATH # Export to sub-processes (make it inherited by child processes)

# Key bindings
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
    bindkey "^[[A" history-substring-search-up
    bindkey "^[[B" history-substring-search-down
fi
