#!/usr/bin/env zsh

if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
  source "$XDG_CACHE_HOME/p10k-instant-prompt-${(%):-%n}.zsh"
fi

if [[ -f "$ZDOTDIR/.p10k.zsh" ]]; then
  source "$ZDOTDIR/.p10k.zsh"
fi

if [[ -f "$XDG_DATA_HOME/zap/zap.zsh" ]]; then
  source "$XDG_DATA_HOME/zap/zap.zsh"
fi

plug "zap-zsh/supercharge" # Must be first for other plugins to work
plug "agkozak/zsh-z"
plug "chivalryq/git-alias"
plug "$ZDOTDIR/aliases.zsh"

if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
  plug "romkatv/powerlevel10k"
  plug "zsh-users/zsh-autosuggestions"
  plug "zsh-users/zsh-history-substring-search"
  plug "zsh-users/zsh-syntax-highlighting"
fi

if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
  bindkey "^[[A" history-substring-search-up
  bindkey "^[[B" history-substring-search-down
fi
