add_newline = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[x](bold red)"

[cmd_duration]
min_time = 10_000

# [directory]
# fish_style_pwd_dir_length = 1
# repo_root_style = "bold yellow"
# truncation_length = 2

[git_commit]
tag_disabled = false

[java]
disabled = true

[line_break]
disabled = true

[memory_usage]
disabled = false
style = "bold dimmed yellow"

[nodejs]
disabled = true

[ruby]
disabled = true

[sudo]
disabled = false
