"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[cmd_duration]
min_time = 2_500

[git_commit]
tag_disabled = false

[java]
disabled = true

[line_break]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[sudo]
disabled = false
